### ISSUE TITLE
Solucionar error "getaddrinfo ENOTFOUND"

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/github-city-rankings-automated#5]
/home/iblancasa/Proyectos/github-city-rankings-automated/lib/utils-node.js:15
          if (error) throw new Error(error);
                           ^
Error: Error: getaddrinfo ENOTFOUND
  at /home/iblancasa/Proyectos/github-city-rankings-automated/lib/utils-node.js:15:28
  at Request.callback (/home/iblancasa/Proyectos/github-city-rankings-automated/node_modules/superagent/lib/node/index.js:603:30)
  at ClientRequest.<anonymous> (/home/iblancasa/Proyectos/github-city-rankings-automated/node_modules/superagent/lib/node/index.js:571:10)
  at ClientRequest.EventEmitter.emit (events.js:95:17)
  at CleartextStream.socketErrorListener (http.js:1547:9)
  at CleartextStream.EventEmitter.emit (events.js:95:17)
  at Socket.onerror (tls.js:1445:17)
  at Socket.EventEmitter.emit (events.js:117:20)
  at net.js:830:16
  at process._tickCallback (node.js:415:13)

**Comment by iblancasa** [comment]
Arreglado.
[Si se ignoran los errores, se genera el fichero (aunque parece que falta algún usuario -el del fallo-)](https://github.com/iblancasa/github-city-rankings-automated/commit/585a7ac4a7457ade24ca772d664cab95fc5175f0)
